services:
  mongodb:
    hostname: mongodb
    image: mongodb/mongodb-atlas-local
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_USER:-user}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-pass}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: mongosh --eval 'db.adminCommand("ping")' --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_API_PORT:-4000}:4000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=4000
      - DB_URL=mongodb://${MONGO_USER:-user}:${MONGO_PASSWORD:-pass}@mongodb:27017/yenshow?directConnection=true&authSource=admin
      - MONGO_URI=mongodb://${MONGO_USER:-user}:${MONGO_PASSWORD:-pass}@mongodb:27017/yenshow?directConnection=true&authSource=admin
      - JWT_SECRET=${JWT_SECRET:-qwiektfgjwqeinjgmqiprhgnjqipw}
      - CORS_ORIGIN=${LAN_CORS_ORIGINS}
      - HOST=0.0.0.0
      - FILES_ROOT=/app/storage
      - API_BASE_URL=http://localhost:${DOCKER_API_PORT:-4000}
      - PUBLIC_BASE_URL=https://api.yenshow.com
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM_ADDRESS_RESEND=${EMAIL_FROM_ADDRESS_RESEND}
      - EMAIL_FROM_NAME_RESEND=${EMAIL_FROM_NAME_RESEND}
      - CONTACT_EMAIL_RECIPIENT=${CONTACT_EMAIL_RECIPIENT}
      - CONTACT_EMAIL_CC=${CONTACT_EMAIL_CC}
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - GA_MEASUREMENT_ID=${GA_MEASUREMENT_ID}
      - GA_API_SECRET=${GA_API_SECRET}
    volumes:
      - D:/storage:/app/storage
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4000/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
        - VITE_API=/api
    ports:
      - "${DOCKER_CLIENT_PORT:-3000}:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - D:/storage:/mnt/storage:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  mongo_data:
  mongo_config:

networks:
  app-network:
    driver: bridge
